export const GLOSSARY_SECTIONS = [
  { id: "income", label: "손익계산서" },
  { id: "balance", label: "재무상태표" },
  { id: "cashflow", label: "현금흐름표" },
  { id: "metrics", label: "비율·밸류" },
  { id: "reading", label: "읽는 법·약어" },
  { id: "sec", label: "SEC 공시" },
] as const;

export type GlossarySectionId = (typeof GLOSSARY_SECTIONS)[number]["id"];

export type GlossaryEntry = {
  id: string;
  section: GlossarySectionId;
  en: string;
  ko: string;
  aliases: readonly string[];
  formula?: string;
  body: string;
  /** 암기 표에 쓰는 영어 표기. 없으면 en에서 안전하게 줄임. */
  word?: string;
};

function looksLikeAbbrev(raw: string): boolean {
  const t = String(raw ?? "").trim();
  if (t.length < 2 || t.length > 22) return false;
  if (/^(add-?back|expense|loss|equity|net)$/i.test(t)) return false;
  if (/^[A-Z]{2,8}(\s*\/\s*[A-Z]{2,8})+$/.test(t)) return true;
  if (/^[A-Z]{2,12}$/.test(t)) return true;
  if (/^[A-Z][a-z]+[A-Z][a-zA-Z]*$/.test(t)) return true;
  if (/^[A-Z0-9]{1,5}[&/.\-][A-Z0-9]{1,10}$/i.test(t)) return true;
  if (/^\d{1,2}-[A-Z](\/[A-Z])?$/i.test(t)) return true;
  return false;
}

/** 암기 표 영어 칸. P/E·P/B처럼 슬래시가 있는 약어를 P로 자르지 않는다. */
export function glossaryMemoWord(entry: GlossaryEntry): string {
  const explicit = String(entry.word ?? "").trim();
  if (explicit) return explicit;
  const en = String(entry.en ?? "").trim();
  const paren = en.match(/\(([^)]{1,28})\)/);
  if (paren && looksLikeAbbrev(paren[1])) {
    return paren[1].replace(/\s+/g, " ").trim();
  }
  return en.split(/\s+[—–]\s+|\s+\/\s+/)[0]?.trim() || en;
}

export const US_FINANCIAL_GLOSSARY: readonly GlossaryEntry[] = [
  // —— 손익계산서 ——
  {
    id: "revenue",
    section: "income",
    en: "Revenue / Net Sales / Total Net Sales",
    ko: "매출액",
    aliases: [
      "revenue",
      "net sales",
      "net revenue",
      "total net sales",
      "total revenue",
      "sales",
      "top line",
      "매출",
      "매출액",
      "총매출",
      "순매출",
    ],
    body: "제품 판매·서비스 제공 등 본업으로 벌어들인 금액. 반품·할인·매출에누리를 뺀 순액(Net)으로 나오는 경우가 많습니다. 손익계산서의 맨 위(Top line)입니다.",
  },
  {
    id: "cogs",
    section: "income",
    en: "Cost of Goods Sold (COGS) / Cost of Revenue / Cost of Sales",
    ko: "매출원가",
    aliases: [
      "cogs",
      "cost of goods sold",
      "cost of revenue",
      "cost of sales",
      "cost of services",
      "매출원가",
      "매출 원가",
    ],
    body: "그 매출을 만들기 위해 직접 들어간 원가. 제조업은 원자재·공장 인건비·제조 감가, 유통은 매입 원가, SaaS는 호스팅·고객지원 직접비 등이 잡힙니다.",
  },
  {
    id: "gross-profit",
    section: "income",
    en: "Gross Profit / Gross Income",
    ko: "매출총이익",
    aliases: ["gross profit", "gross income", "매출총이익", "매출 총이익", "총이익"],
    formula: "Revenue − COGS",
    body: "제품·서비스 자체의 마진. 여기서 이미 얇으면 아래 SG&A를 아무리 줄여도 본업 수익성이 나오기 어렵습니다.",
  },
  {
    id: "gross-margin",
    section: "income",
    en: "Gross Margin / Gross Profit Margin",
    ko: "매출총이익률",
    aliases: ["gross margin", "gross profit margin", "매출총이익률", "매출 총이익률", "총이익률"],
    formula: "(Gross Profit ÷ Revenue) × 100",
    body: "원가 대비 가격 결정력. 브랜드·규모·독점력이 있으면 높게 유지되고, 원자재 급등·할인 경쟁이면 내려갑니다.",
  },
  {
    id: "opex",
    section: "income",
    en: "Operating Expenses (OpEx)",
    ko: "영업비용",
    aliases: ["operating expenses", "opex", "operating costs", "영업비용", "판매관리비등"],
    body: "본업을 돌리는 데 드는 비용 묶음. 보통 SG&A + R&D + 감가·무형자산상각 + 구조조정 등이 여기 들어갑니다. 매출원가와는 별개입니다.",
  },
  {
    id: "sga",
    section: "income",
    en: "SG&A — Selling, General & Administrative",
    ko: "판매비와 관리비",
    word: "SG&A",
    aliases: [
      "sg&a",
      "sga",
      "selling general administrative",
      "selling general and administrative",
      "selling expense",
      "general and administrative",
      "g&a",
      "판매비와 관리비",
      "판매관리비",
      "판매·관리비",
      "판관비",
    ],
    body: "마케팅·영업사원 급여·본사 임차·관리 인건비·법무 등 ‘팔고 회사를 굴리는’ 간접비. 매출 대비 비중이 계속 커지면 비용 통제가 약해진 신호일 수 있습니다.",
  },
  {
    id: "rnd",
    section: "income",
    en: "Research & Development (R&D)",
    ko: "연구개발비",
    aliases: ["r&d", "rnd", "research and development", "research development", "연구개발비", "연구개발", "r and d"],
    body: "신제품·기술·약을 만들기 위한 비용. 기술·바이오에서는 미래 성장의 원천이지만, 당기 영업이익을 깎습니다. 미국 GAAP는 대부분 발생 시점에 비용 처리합니다.",
  },
  {
    id: "sales-marketing",
    section: "income",
    en: "Sales and Marketing / Advertising Expense",
    ko: "판매비·광고선전비",
    aliases: [
      "sales and marketing",
      "sales & marketing",
      "advertising expense",
      "advertising",
      "marketing expense",
      "판매비",
      "광고선전비",
      "마케팅비",
    ],
    body: "고객을 데려오는 비용. 성장기에는 매출보다 빨리 늘 수 있고, 성숙기에는 매출 대비 비율이 안정되는 편이 건전합니다.",
  },
  {
    id: "sbc-income",
    section: "income",
    en: "Stock-based Compensation (SBC)",
    ko: "주식기준보상 비용",
    aliases: [
      "stock-based compensation",
      "stock based compensation",
      "share-based compensation",
      "sbc",
      "equity compensation",
      "주식기준보상",
      "주식기반보상",
      "주식보상비용",
      "주식보상",
    ],
    body: "스톡옵션·RSU로 준 보상. 현금은 안 나가지만 비용으로 잡히고, 나중에 주식 수가 늘어 주당 가치를 희석합니다. Non-GAAP에서 빼 보여주는 회사가 많아 같이 봐야 합니다.",
  },
  {
    id: "da-income",
    section: "income",
    en: "Depreciation & Amortization (D&A)",
    ko: "감가상각비·무형자산상각비",
    aliases: [
      "depreciation",
      "amortization",
      "d&a",
      "depreciation and amortization",
      "감가상각비",
      "감가상각",
      "무형자산상각",
      "상각비",
    ],
    body: "이미 사 둔 공장·장비(Depreciation)나 특허·소프트웨어(Amortization)의 가치를 여러 해에 나눠 비용으로 인식. 현금 유출은 예전에 CapEx로 나갔습니다.",
  },
  {
    id: "impairment",
    section: "income",
    en: "Impairment / Write-down / Write-off",
    ko: "손상차손·평가감",
    aliases: [
      "impairment",
      "goodwill impairment",
      "write-down",
      "writedown",
      "write-off",
      "writeoff",
      "asset impairment",
      "손상차손",
      "영업권손상",
      "평가감",
      "감액",
    ],
    body: "자산이 장부가보다 회수 가능성이 낮아져 한 번에 깎는 비용. 영업권 손상은 M&A를 비싸게 산 뒤 기대가 꺾였다는 뜻에 가깝습니다. 비현금이지만 경영진 실수 신호로 봅니다.",
  },
  {
    id: "restructuring",
    section: "income",
    en: "Restructuring Charges / Severance",
    ko: "구조조정 비용",
    aliases: [
      "restructuring",
      "restructuring charges",
      "severance",
      "exit costs",
      "구조조정",
      "구조조정비용",
      "퇴직위로금",
    ],
    body: "사업 정리·감원·공장 폐쇄 비용. ‘일회성’으로 포장되지만 여러 해 반복되면 본업 비용입니다. 현금이 실제로 나가는 항목이 많습니다.",
  },
  {
    id: "operating-income",
    section: "income",
    en: "Operating Income / Income from Operations / Operating Loss",
    ko: "영업이익",
    aliases: [
      "operating income",
      "operating profit",
      "operating loss",
      "income from operations",
      "loss from operations",
      "영업이익",
      "영업손실",
      "영업손익",
    ],
    formula: "Gross Profit − OpEx (SG&A, R&D 등)",
    body: "본업만으로 남긴 이익. 이자·세금·투자손익을 빼기 전입니다. 미국 실적에서 ‘장사가 되는가’를 보는 핵심 줄입니다.",
  },
  {
    id: "operating-margin",
    section: "income",
    en: "Operating Margin",
    ko: "영업이익률",
    aliases: ["operating margin", "operating profit margin", "영업이익률", "영업 이익률"],
    formula: "(Operating Income ÷ Revenue) × 100",
    body: "본업 효율. 같은 업종끼리 비교하고, 한 회사는 여러 해 추세로 봅니다. 일회성 손상·구조조정이 끼면 왜곡됩니다.",
  },
  {
    id: "ebit",
    section: "income",
    en: "EBIT — Earnings Before Interest and Taxes",
    ko: "EBIT (이자·세금 차감 전 이익)",
    aliases: ["ebit", "earnings before interest and taxes", "이자세금차감전이익"],
    body: "이자와 세금을 내기 전 이익. 영업이익과 거의 같게 쓰이지만, 영업외 항목 포함 여부는 회사마다 다릅니다. 자본구조(부채 비중)를 빼고 비교할 때 씁니다.",
  },
  {
    id: "ebitda",
    section: "income",
    en: "EBITDA",
    ko: "EBITDA (상각전 영업이익)",
    aliases: [
      "ebitda",
      "earnings before interest taxes depreciation and amortization",
      "adjusted ebitda",
      "조정ebitda",
    ],
    formula: "EBIT + Depreciation + Amortization",
    body: "감가·무형자산상각을 더해 현금창출력에 가깝게 본 비GAAP 지표. 설비 산업 비교에 자주 쓰이지만 CapEx·SBC·운전자본은 빠져 있어 ‘진짜 현금’은 아닙니다.",
  },
  {
    id: "interest-expense",
    section: "income",
    en: "Interest Expense",
    ko: "이자비용",
    aliases: ["interest expense", "interest cost", "finance costs", "이자비용", "금융비용", "이자 비용"],
    body: "차입금·회사채에 내는 이자. 금리가 오르거나 부채가 늘면 커집니다. 영업이익으로 이자를 감당 못 하면 재무 위험이 커집니다.",
  },
  {
    id: "interest-income",
    section: "income",
    en: "Interest Income / Interest and Other Income",
    ko: "이자수익",
    aliases: [
      "interest income",
      "interest and other income",
      "other income",
      "이자수익",
      "이자 수익",
      "영업외수익",
    ],
    body: "현금·국채 등에서 나온 이자. 현금이 많은 빅테크는 이 줄이 큽니다. 본업 실적과 섞어 보면 안 됩니다.",
  },
  {
    id: "other-income",
    section: "income",
    en: "Other Income (Expense), net",
    ko: "기타 수익(비용)",
    word: "Other Income, net",
    aliases: ["other income", "other expense", "other income expense net", "기타수익", "기타비용", "영업외손익"],
    body: "본업 밖 잡손익. 자산 매각차익, 환율, 투자자산 평가 등이 들어갑니다. 갑자기 커지면 일회성인지 주석을 봅니다.",
  },
  {
    id: "equity-method",
    section: "income",
    en: "Equity in Earnings of Affiliates / Income from Equity Method",
    ko: "지분법이익",
    aliases: [
      "equity in earnings",
      "equity method",
      "income from equity method",
      "earnings of affiliates",
      "지분법",
      "지분법이익",
      "관계기업손익",
    ],
    body: "20~50% 안팎 지분 회사의 순이익을 지분율만큼 반영. 현금 배당과 금액이 다를 수 있습니다. 버크셔 등 투자 회사 손익에서 자주 보입니다.",
  },
  {
    id: "fx-gain",
    section: "income",
    en: "Foreign Exchange Gain (Loss)",
    ko: "외환차손익",
    aliases: [
      "foreign exchange",
      "fx gain",
      "fx loss",
      "currency translation",
      "외환차손",
      "외환차익",
      "외환환산",
    ],
    body: "달러 외 통화 자산·부채를 다시 환산하면서 생기는 손익. 본업과 무관한 변동이 커서, 추세를 볼 때는 제외하고 보는 경우가 많습니다.",
  },
  {
    id: "pretax",
    section: "income",
    en: "Income Before Tax / Pretax Income / EBT",
    ko: "법인세차감전이익",
    aliases: [
      "income before tax",
      "income before income taxes",
      "pretax income",
      "pre-tax income",
      "earnings before tax",
      "ebt",
      "법인세차감전이익",
      "세전이익",
      "법인세 차감전 이익",
    ],
    body: "법인세만 빼기 전 이익. 영업이익에서 이자·기타손익을 반영한 뒤입니다. 실효세율 = 세금 ÷ 이 금액.",
  },
  {
    id: "tax-expense",
    section: "income",
    en: "Income Tax Expense / Provision for Income Taxes",
    ko: "법인세 비용",
    aliases: [
      "income tax expense",
      "income tax",
      "provision for income taxes",
      "tax provision",
      "tax benefit",
      "법인세",
      "법인세비용",
      "법인세 비용",
    ],
    body: "그 기간 이익에 대한 세금. 현금으로 낸 세금(현금흐름표)과 다를 수 있습니다. 이연법인세·세액공제·해외 세율이 끼면 괴리가 납니다.",
  },
  {
    id: "etr",
    section: "income",
    en: "Effective Tax Rate (ETR)",
    ko: "실효세율",
    aliases: ["effective tax rate", "etr", "tax rate", "실효세율", "유효세율"],
    formula: "Income Tax Expense ÷ Pretax Income",
    body: "법정 세율이 아니라 실제로 적용된 세율. 해외 이익 비중, R&D 세액공제, 일회성 세무 효과가 움직입니다.",
  },
  {
    id: "continuing-ops",
    section: "income",
    en: "Income from Continuing Operations",
    ko: "계속사업이익",
    aliases: ["continuing operations", "income from continuing operations", "계속사업", "계속사업이익"],
    body: "앞으로도 남길 사업에서 난 이익. 매각·중단한 사업(Discontinued operations)을 빼고 본업 추세를 볼 때 이 줄을 씁니다.",
  },
  {
    id: "discontinued",
    section: "income",
    en: "Discontinued Operations",
    ko: "중단사업손익",
    aliases: ["discontinued operations", "discontinued", "중단사업", "중단영업"],
    body: "팔았거나 곧 팔 사업의 손익을 따로 표시. 본업 성장률을 계산할 때는 빼는 것이 맞습니다.",
  },
  {
    id: "net-income",
    section: "income",
    en: "Net Income / Net Earnings / Net Loss",
    ko: "당기순이익",
    aliases: [
      "net income",
      "net earnings",
      "net profit",
      "net loss",
      "net income common stockholders",
      "bottom line",
      "당기순이익",
      "순이익",
      "당기순손실",
      "순손실",
    ],
    body: "모든 비용·이자·세금을 뺀 최종 이익(Bottom line). 주주 몫입니다. 비현금 손상·SBC가 크면 현금흐름과 어긋날 수 있어 OCF와 같이 봅니다.",
  },
  {
    id: "nci-income",
    section: "income",
    en: "Net Income Attributable to Noncontrolling Interests",
    ko: "비지배지분 순이익",
    aliases: [
      "noncontrolling interest",
      "minority interest",
      "nci",
      "attributable to noncontrolling",
      "비지배지분",
      "소수주주지분",
    ],
    body: "자회사를 100% 안 가진 경우, 바깥 주주 몫의 이익. 지배주주 순이익 = 전체 순이익 − 이 줄.",
  },
  {
    id: "preferred-div",
    section: "income",
    en: "Preferred Dividends",
    ko: "우선주 배당",
    aliases: ["preferred dividends", "preferred stock dividends", "우선주배당", "우선주 배당"],
    body: "우선주 주주에게 먼저 주는 배당. 보통주 EPS를 계산할 때 순이익에서 빼집니다.",
  },
  {
    id: "eps-basic",
    section: "income",
    en: "Basic EPS",
    ko: "기본 주당순이익",
    aliases: ["basic eps", "eps basic", "earnings per share basic", "기본eps", "기본 주당순이익", "주당순이익"],
    formula: "Net Income ÷ Weighted Average Shares (기본)",
    body: "그 기간 평균 발행주식으로 나눈 주당 이익. 옵션·전환증권은 아직 넣지 않습니다.",
  },
  {
    id: "eps-diluted",
    section: "income",
    en: "Diluted EPS",
    ko: "희석 주당순이익",
    aliases: [
      "diluted eps",
      "eps diluted",
      "eps",
      "earnings per share",
      "희석eps",
      "희석 주당순이익",
      "eps (주당순이익)",
    ],
    formula: "Net Income ÷ Diluted Weighted Average Shares",
    body: "스톡옵션·RSU·전환사채가 주식으로 바뀐다고 가정한 EPS. 미국 실적·PER의 기본 분모입니다. Basic보다 작거나 같습니다.",
  },
  {
    id: "weighted-shares",
    section: "income",
    en: "Weighted Average Shares Outstanding",
    ko: "가중평균 유통주식 수",
    aliases: [
      "weighted average shares",
      "shares outstanding",
      "diluted shares",
      "basic shares",
      "가중평균주식수",
      "유통주식수",
      "주식수",
    ],
    body: "기간 중 주식 수 변동(증자·자사주)을 시간 가중으로 평균. EPS 분모입니다. 자사주 매입이 많으면 이 수가 줄고 EPS가 올라갑니다.",
  },
  {
    id: "oci",
    section: "income",
    en: "Other Comprehensive Income (OCI)",
    ko: "기타포괄손익",
    aliases: ["other comprehensive income", "oci", "comprehensive income", "기타포괄손익", "총포괄손익", "포괄손익"],
    body: "당기순이익에는 안 넣고 자본에 바로 넣는 평가손익. 매도가능증권 평가, 해외사업 환산, 연금 재측정 등. 총포괄이익 = 순이익 + OCI.",
  },
  {
    id: "non-gaap",
    section: "income",
    en: "Non-GAAP / Adjusted Earnings",
    ko: "비GAAP·조정 이익",
    aliases: [
      "non-gaap",
      "nongaap",
      "adjusted earnings",
      "adjusted net income",
      "adjusted eps",
      "비gaap",
      "조정이익",
      "조정eps",
    ],
    body: "회사 임의로 일회성·SBC·무형자산상각 등을 뺀 이익. 본업을 보기 쉽지만 빼는 항목이 해마다 달라질 수 있어 GAAP 순이익과 같이 봅니다.",
  },
  {
    id: "net-interest-income",
    section: "income",
    en: "Net Interest Income (NII)",
    ko: "순이자이익",
    aliases: ["net interest income", "nii", "net interest margin", "nim", "순이자이익", "순이자마진"],
    body: "은행의 핵심 매출에 해당. 대출 이자수익 − 예수금 이자비용. NIM은 이를 이자부자산으로 나눈 마진입니다.",
  },
  {
    id: "credit-loss",
    section: "income",
    en: "Provision for Credit Losses / PCL",
    ko: "대손충당금 전입",
    aliases: [
      "provision for credit losses",
      "credit loss",
      "pcl",
      "loan loss provision",
      "allowance for credit losses",
      "대손충당금",
      "대손상각",
      "신용손실",
    ],
    body: "은행·카드사가 빌려준 돈이 떼일 것에 대비해 미리 쌓는 비용. 경기가 나빠질 때 급증해 순이익을 깎습니다.",
  },
  {
    id: "premiums-earned",
    section: "income",
    en: "Premiums Earned",
    ko: "경과보험료",
    aliases: ["premiums earned", "insurance premiums", "net premiums", "경과보험료", "수입보험료"],
    body: "받은 보험료 중 해당 기간에 보장 서비스를 제공한 분. 미리 받은 보험료는 부채(이연수익)로 남아 있습니다.",
  },
  {
    id: "underwriting",
    section: "income",
    en: "Underwriting Income / Combined Ratio",
    ko: "보험 인수손익·합산비율",
    aliases: ["underwriting", "combined ratio", "loss ratio", "인수손익", "합산비율", "손해율"],
    body: "보험료로 사고·사업비를 감당하고 남긴 손익. 합산비율 100% 미만이면 보험 본업이 흑자입니다.",
  },

  // —— 재무상태표 ——
  {
    id: "cash",
    section: "balance",
    en: "Cash and Cash Equivalents",
    ko: "현금 및 현금성자산",
    aliases: ["cash", "cash and cash equivalents", "cash equivalents", "현금", "현금성자산", "현금및현금성자산"],
    body: "즉시 쓸 수 있는 현금과 만기 3개월 이내 단기 금융상품. 유동성의 출발점입니다.",
  },
  {
    id: "restricted-cash",
    section: "balance",
    en: "Restricted Cash",
    ko: "사용제한 현금",
    aliases: ["restricted cash", "사용제한현금", "제한현금"],
    body: "담보·에스크로·규제 때문에 마음대로 못 쓰는 현금. 총현금에 포함돼 보여도 ‘쓸 수 있는 돈’에서 빼야 합니다.",
  },
  {
    id: "marketable",
    section: "balance",
    en: "Marketable Securities / Short-term Investments",
    ko: "단기투자자산·유가증권",
    aliases: [
      "marketable securities",
      "short-term investments",
      "short term investments",
      "available-for-sale",
      "trading securities",
      "단기투자",
      "단기매매증권",
      "유가증권",
      "매도가능증권",
    ],
    body: "여유 자금을 국채·회사채·상장주식 등에 넣어 둔 것. 현금에 가깝지만 가격 변동이 있습니다. 빅테크 ‘현금 더미’의 상당 부분이 여기입니다.",
  },
  {
    id: "ar",
    section: "balance",
    en: "Accounts Receivable (A/R) / Trade Receivables",
    ko: "매출채권",
    aliases: [
      "accounts receivable",
      "trade receivables",
      "receivables",
      "a/r",
      "ar",
      "net receivables",
      "매출채권",
      "외상매출금",
    ],
    body: "물건을 팔고 아직 못 받은 돈. 매출보다 빨리 늘면 회수가 늦거나 무리한 외상 판매일 수 있습니다. 대손충당금을 뺀 순액으로 표시됩니다.",
  },
  {
    id: "allowance-doubtful",
    section: "balance",
    en: "Allowance for Doubtful Accounts / ACL",
    ko: "대손충당금",
    aliases: [
      "allowance for doubtful accounts",
      "allowance for credit losses",
      "acl",
      "bad debt allowance",
      "대손충당금",
    ],
    body: "매출채권 중 못 받을 것으로 예상해 미리 깎아 둔 금액. 자산에서 차감합니다.",
  },
  {
    id: "inventory",
    section: "balance",
    en: "Inventories",
    ko: "재고자산",
    aliases: [
      "inventory",
      "inventories",
      "raw materials",
      "work in progress",
      "finished goods",
      "재고자산",
      "재고",
      "원재료",
      "재공품",
      "제품",
    ],
    body: "원재료·재공품·완제품. 안 팔리면 현금이 묶이고, 오래되면 평가감이 납니다. 제조·유통에서 핵심 운전자본입니다.",
  },
  {
    id: "prepaid",
    section: "balance",
    en: "Prepaid Expenses / Other Current Assets",
    ko: "선급비용·기타유동자산",
    aliases: ["prepaid expenses", "prepaids", "other current assets", "선급비용", "선급금", "기타유동자산"],
    body: "보험료·임차료처럼 미리 낸 돈, 또는 1년 안에 현금화될 기타 자산. 보통 크지 않지만 갑자기 늘면 내용을 봅니다.",
  },
  {
    id: "current-assets",
    section: "balance",
    en: "Total Current Assets",
    ko: "유동자산 합계",
    aliases: ["current assets", "total current assets", "유동자산", "유동자산합계"],
    body: "1년(또는 영업순환주기) 안에 현금화될 자산. 현금 + 단기투자 + 매출채권 + 재고 등. 단기 지급 능력의 분자입니다.",
  },
  {
    id: "ppe",
    section: "balance",
    en: "Property, Plant & Equipment (PP&E)",
    ko: "유형자산",
    aliases: [
      "ppe",
      "pp&e",
      "property plant and equipment",
      "property plant equipment",
      "fixed assets",
      "유형자산",
      "설비자산",
    ],
    body: "토지·건물·기계·서버 등 실물 설비. 총액에서 감가상각누계액을 뺀 순액으로 나옵니다. 토지는 보통 상각하지 않습니다.",
  },
  {
    id: "accum-dep",
    section: "balance",
    en: "Accumulated Depreciation",
    ko: "감가상각누계액",
    aliases: ["accumulated depreciation", "accum dep", "감가상각누계액", "감가상각누계"],
    body: "지금까지 쌓인 유형자산 상각. PP&E 총액에서 이 금액을 빼 순액을 만듭니다. 자산 반대(차감) 계정입니다.",
  },
  {
    id: "rou-asset",
    section: "balance",
    en: "Operating Lease Right-of-Use Asset",
    ko: "사용권자산 (리스)",
    aliases: ["right-of-use", "rou", "operating lease asset", "사용권자산", "리스자산"],
    body: "사무실·매장 임차를 자산으로 올린 것(ASC 842). 맞은편에 리스부채가 있습니다. 예전에 없던 줄이라 총자산·부채가 커 보일 수 있습니다.",
  },
  {
    id: "goodwill",
    section: "balance",
    en: "Goodwill",
    ko: "영업권",
    aliases: ["goodwill", "영업권"],
    body: "M&A 때 순자산 공정가치보다 더 준 돈. 브랜드·인력·시너지 기대치입니다. 매년 손상검사만 하고 정액 상각하지 않습니다. 손상 나면 한 번에 이익이 깎입니다.",
  },
  {
    id: "intangibles",
    section: "balance",
    en: "Intangible Assets",
    ko: "무형자산",
    aliases: ["intangible assets", "intangibles", "patents", "trademarks", "customer relationships", "무형자산", "특허권", "상표권"],
    body: "특허·상표·소프트웨어·고객관계 등. 영업권과 달리 유한 수명이면 상각합니다. 자체 개발 브랜드는 보통 장부에 안 올라갑니다.",
  },
  {
    id: "lt-investments",
    section: "balance",
    en: "Long-term Investments / Equity Method Investments",
    ko: "장기투자자산",
    aliases: [
      "long-term investments",
      "long term investments",
      "equity method investments",
      "장기투자",
      "장기투자자산",
      "관계기업투자",
    ],
    body: "만기 1년 넘는 채권·지분법 적용 관계회사 지분 등. 버크셔처럼 투자 비중이 큰 회사의 핵심 자산입니다.",
  },
  {
    id: "deferred-tax-asset",
    section: "balance",
    en: "Deferred Tax Assets (DTA)",
    ko: "이연법인세자산",
    aliases: ["deferred tax assets", "dta", "이연법인세자산"],
    body: "장부 세금이 나중에 줄어들 것으로 기대되는 자산. 이월결손금 등이 원인입니다. 실현이 불확실하면 평가충당(Valuation allowance)으로 깎습니다.",
  },
  {
    id: "total-assets",
    section: "balance",
    en: "Total Assets",
    ko: "총자산",
    aliases: ["total assets", "assets", "총자산"],
    formula: "Liabilities + Equity",
    body: "회사가 보유한 모든 자산. 재무상태표의 균형: 자산 = 부채 + 자본.",
  },
  {
    id: "ap",
    section: "balance",
    en: "Accounts Payable (A/P) / Trade Payables",
    ko: "매입채무",
    aliases: ["accounts payable", "trade payables", "payables", "a/p", "ap", "매입채무", "외상매입금"],
    body: "원재료·외주를 사고 아직 안 준 돈. 늘면 단기적으로 현금이 남지만, 너무 늘면 협력사 관계·지급 능력 신호일 수 있습니다.",
  },
  {
    id: "accrued",
    section: "balance",
    en: "Accrued Expenses / Accrued Liabilities",
    ko: "미지급비용",
    aliases: ["accrued expenses", "accrued liabilities", "accruals", "미지급비용", "미지급금", "선수금외"],
    body: "이미 발생했지만 아직 청구서가 안 온 비용. 임금, 이자, 세금, 보너스 등. 발생주의의 부채 쪽입니다.",
  },
  {
    id: "st-debt",
    section: "balance",
    en: "Short-term Debt / Current Portion of Long-term Debt",
    ko: "단기차입금·유동성장기부채",
    aliases: [
      "short-term debt",
      "short term debt",
      "current portion",
      "current portion of long-term debt",
      "short long term debt",
      "단기차입금",
      "유동성장기부채",
      "유동성 장기부채",
    ],
    body: "1년 안에 갚아야 하는 차입금 + 장기부채 중 올해 만기 도래분. 현금이 부족하면 차환(돌려막기) 리스크입니다.",
  },
  {
    id: "deferred-rev",
    section: "balance",
    en: "Deferred Revenue / Unearned Revenue / Contract Liabilities",
    ko: "이연수익·선수수익",
    aliases: [
      "deferred revenue",
      "unearned revenue",
      "unearned",
      "contract liabilities",
      "deferred income",
      "이연수익",
      "선수수익",
      "선수금",
      "계약부채",
    ],
    body: "돈은 받았는데 아직 제품·서비스를 덜 준 부채. 구독·선수금 모델에서 큽니다. 늘면 미래 매출의 파이프라인이 쌓인 것으로 읽습니다.",
  },
  {
    id: "lease-liab",
    section: "balance",
    en: "Operating Lease Liabilities",
    ko: "리스부채",
    aliases: ["lease liabilities", "operating lease liabilities", "리스부채", "운용리스부채"],
    body: "임차 의무의 현재가치. 유동(1년 내 지급분)과 비유동으로 나뉩니다. 사용권자산과 쌍입니다.",
  },
  {
    id: "tax-payable",
    section: "balance",
    en: "Income Taxes Payable",
    ko: "미지급법인세",
    aliases: ["income taxes payable", "taxes payable", "미지급법인세", "미지급세금"],
    body: "이미 발생한 법인세 중 아직 납부하지 않은 금액.",
  },
  {
    id: "current-liab",
    section: "balance",
    en: "Total Current Liabilities",
    ko: "유동부채 합계",
    aliases: ["current liabilities", "total current liabilities", "유동부채", "유동부채합계"],
    body: "1년 안에 갚을 채무 합계. 유동비율·당좌비율의 분모입니다.",
  },
  {
    id: "lt-debt",
    section: "balance",
    en: "Long-term Debt / Notes Payable",
    ko: "장기차입금",
    aliases: [
      "long-term debt",
      "long term debt",
      "notes payable",
      "bonds payable",
      "장기부채",
      "장기차입금",
      "사채",
    ],
    body: "만기 1년 넘는 은행 차입·회사채. 이자비용의 원천입니다. 만기 일정(주석)을 봐야 차환 위험을 압니다.",
  },
  {
    id: "deferred-tax-liab",
    section: "balance",
    en: "Deferred Tax Liabilities (DTL)",
    ko: "이연법인세부채",
    aliases: ["deferred tax liabilities", "dtl", "이연법인세부채"],
    body: "장부 이익이 세무 이익보다 빨라 나중에 세금을 더 낼 의무. 감가 방법 차이 등이 원인입니다.",
  },
  {
    id: "pension",
    section: "balance",
    en: "Pension / Postretirement Benefit Obligations",
    ko: "퇴직급여충당부채",
    aliases: ["pension", "postretirement", "defined benefit", "퇴직급여", "연금부채", "확정급여"],
    body: "확정급여형 연금·의료의 부족분. 금리·수익률 가정이 바뀌면 크게 움직입니다. 제조·항공·자동차 주석에서 자주 봅니다.",
  },
  {
    id: "contingent",
    section: "balance",
    en: "Contingent Liabilities / Commitments",
    ko: "우발부채·약정",
    aliases: ["contingent liabilities", "commitments", "contingencies", "우발부채", "우발채무", "약정"],
    body: "소송·보증처럼 아직 확정되지 않은 의무. 금액이 추정 가능하고 개연성이 높으면 부채로 올리고, 아니면 주석만 답니다. 숫자 표보다 주석이 본문입니다.",
  },
  {
    id: "total-liab",
    section: "balance",
    en: "Total Liabilities",
    ko: "총부채",
    aliases: ["total liabilities", "total liab", "liabilities", "총부채"],
    body: "유동+비유동 부채 합계. 남이 회사에 대해 갖는 청구권입니다.",
  },
  {
    id: "common-stock",
    section: "balance",
    en: "Common Stock / Preferred Stock",
    ko: "보통주·우선주 자본금",
    word: "Common/Preferred Stock",
    aliases: ["common stock", "preferred stock", "share capital", "보통주", "우선주", "자본금"],
    body: "액면가 × 발행주식 수 수준의 자본금. 미국은 액면이 거의 0에 가까워 금액이 작습니다. 실제 납입 초과분은 APIC로 갑니다.",
  },
  {
    id: "apic",
    section: "balance",
    en: "Additional Paid-in Capital (APIC) / Capital Surplus",
    ko: "주식발행초과금",
    aliases: [
      "additional paid-in capital",
      "additional paid in capital",
      "apic",
      "capital surplus",
      "paid-in capital",
      "주식발행초과금",
      "자본잉여금",
    ],
    body: "주식을 액면보다 비싸게 발행해 받은 돈. IPO·유상증자·옵션 행사 때 쌓입니다.",
  },
  {
    id: "retained",
    section: "balance",
    en: "Retained Earnings",
    ko: "이익잉여금",
    aliases: ["retained earnings", "accumulated deficit", "이익잉여금", "결손금", "미처분이익잉여금"],
    body: "설립 이후 순이익을 쌓고 배당·자사주를 뺀 잔액. 적자가 누적되면 Accumulated deficit(결손)으로 음수가 됩니다.",
  },
  {
    id: "aoci",
    section: "balance",
    en: "Accumulated Other Comprehensive Income (AOCI)",
    ko: "기타포괄손익누계액",
    aliases: ["aoci", "accumulated other comprehensive income", "기타포괄손익누계액", "기타포괄손익누계"],
    body: "OCI가 자본에 쌓인 누계. 환율·증권평가·연금 재측정 등. 당기순이익과 별개로 자본을 흔듭니다.",
  },
  {
    id: "treasury",
    section: "balance",
    en: "Treasury Stock",
    ko: "자기주식",
    aliases: ["treasury stock", "treasury shares", "자기주식", "자사주"],
    body: "회사가 사들여 보유 중인 자기 주식. 자본에서 빼는(차감) 항목입니다. 소각하면 주식 수가 줄고, 보유만 하면 나중에 재발행할 수 있습니다.",
  },
  {
    id: "equity",
    section: "balance",
    en: "Total Shareholders' Equity / Stockholders' Equity",
    ko: "총자본 (주주지분)",
    aliases: [
      "shareholders equity",
      "stockholders equity",
      "total equity",
      "book value",
      "총자본",
      "자본총계",
      "주주지분",
      "자기자본",
    ],
    formula: "Total Assets − Total Liabilities",
    body: "주주 몫의 순자산. BPS의 분자입니다. 자사주 매입·배당·적자로 줄어들고, 이익·증자로 늘어납니다.",
  },
  {
    id: "nci-equity",
    section: "balance",
    en: "Noncontrolling Interest (Equity)",
    ko: "비지배지분 (자본)",
    aliases: ["noncontrolling interest equity", "minority interest equity", "비지배지분자본"],
    body: "연결 자회사의 바깥 주주 몫 자본. 총자본에 포함되지만 모회사 주주 순자산과는 구분합니다.",
  },
  {
    id: "working-capital",
    section: "balance",
    en: "Working Capital",
    ko: "운전자본",
    aliases: ["working capital", "net working capital", "nwc", "운전자본", "순운전자본"],
    formula: "Current Assets − Current Liabilities",
    body: "일상 영업에 묶이거나 필요한 단기 자금. 너무 작으면 지급 위험이, 너무 크면 재고·외상이 과할 수 있습니다.",
  },
  {
    id: "net-debt",
    section: "balance",
    en: "Net Debt",
    ko: "순부채",
    aliases: ["net debt", "net cash", "순부채", "순현금"],
    formula: "총차입금 − 현금성자산(−단기투자)",
    body: "이자 나는 부채에서 현금을 뺀 값. 음수면 순현금입니다. EV 계산에 들어갑니다.",
  },

  // —— 현금흐름표 ——
  {
    id: "ocf",
    section: "cashflow",
    en: "Operating Cash Flow (OCF / CFO)",
    ko: "영업활동 현금흐름",
    aliases: [
      "operating cash flow",
      "ocf",
      "cfo",
      "cash from operations",
      "total cash from operating activities",
      "영업활동현금흐름",
      "영업현금흐름",
      "영업활동 현금흐름",
    ],
    body: "본업에서 실제로 들어온 현금. 간접법은 순이익에서 시작해 감가·SBC를 더하고 운전자본 증감을 반영합니다. 순이익과 괴리가 크면 이익의 질을 의심합니다.",
  },
  {
    id: "indirect-cfo",
    section: "cashflow",
    en: "Indirect Method — starting at Net Income",
    ko: "간접법 (순이익에서 조정)",
    aliases: ["indirect method", "간접법"],
    body: "미국 거의 모든 회사가 쓰는 영업현금 표시법. 순이익 + 비현금비용 −/+ 운전자본 변동 = OCF.",
  },
  {
    id: "wc-change",
    section: "cashflow",
    en: "Changes in Working Capital",
    ko: "운전자본 증감",
    aliases: [
      "changes in working capital",
      "change in receivables",
      "change in inventory",
      "change in payables",
      "운전자본증감",
      "매출채권의증가",
      "재고자산의증가",
    ],
    body: "매출채권·재고가 늘면 현금이 묶여 OCF가 줄고, 매입채무·이연수익이 늘면 OCF가 늘어납니다. 성장기에는 채권·재고 증가가 흔합니다.",
  },
  {
    id: "da-cfo",
    section: "cashflow",
    en: "Depreciation & Amortization (add-back)",
    ko: "감가·상각 가산 (현금흐름)",
    word: "D&A (OCF 가산)",
    aliases: ["depreciation add back", "amortization add back"],
    body: "손익에 비용으로 넣었지만 현금이 안 나갔으므로 OCF에 다시 더합니다. 설비 투자의 현금은 투자활동(CapEx)에 따로 나갑니다.",
  },
  {
    id: "sbc-cfo",
    section: "cashflow",
    en: "Stock-based Compensation (add-back)",
    ko: "주식보상 가산 (현금흐름)",
    word: "SBC (OCF 가산)",
    aliases: ["stock based compensation add back", "sbc add back"],
    body: "비현금 비용이라 OCF에 더해집니다. 그래서 SBC가 큰 회사는 OCF가 좋아 보여도 주주 희석은 진행 중입니다.",
  },
  {
    id: "deferred-tax-cfo",
    section: "cashflow",
    en: "Deferred Income Taxes (cash flow)",
    ko: "이연법인세 (현금흐름 조정)",
    aliases: ["deferred income taxes", "deferred taxes", "이연법인세"],
    body: "손익의 세금과 실제로 낸 세금의 차이. 가산이면 장부 세금이 현금 세금보다 많다는 뜻입니다.",
  },
  {
    id: "icf",
    section: "cashflow",
    en: "Investing Cash Flow (ICF / CFI)",
    ko: "투자활동 현금흐름",
    aliases: [
      "investing cash flow",
      "icf",
      "cfi",
      "cash from investing",
      "total cash from investing activities",
      "투자활동현금흐름",
      "투자현금흐름",
      "투자활동 현금흐름",
    ],
    body: "설비 구매, M&A, 유가증권 매매. 성장하는 회사는 보통 큰 음수입니다. 양수가 계속이면 자산을 팔아 연명하는 경우도 있어 내역을 봅니다.",
  },
  {
    id: "capex",
    section: "cashflow",
    en: "Capital Expenditures (CapEx) / Purchases of PP&E",
    ko: "자본적 지출",
    aliases: [
      "capex",
      "capital expenditures",
      "capital expenditure",
      "purchases of ppe",
      "purchase of property",
      "capex",
      "유형자산의취득",
      "설비투자",
    ],
    body: "공장·장비·데이터센터를 사고 유지하는 현금. 유지 CapEx와 성장 CapEx를 구분하면 좋습니다. FCF 계산에서 OCF에서 빼는 핵심 줄입니다.",
  },
  {
    id: "acquisitions",
    section: "cashflow",
    en: "Acquisitions / Business Combinations / Divestitures",
    ko: "인수·매각",
    aliases: [
      "acquisitions",
      "business combinations",
      "purchase of businesses",
      "divestitures",
      "proceeds from sale of business",
      "인수",
      "사업결합",
      "매각대금",
    ],
    body: "회사·사업부를 사거나 팔 때 오가는 현금. 일회성이 커서 정상 FCF를 볼 때는 따로 빼 보기도 합니다.",
  },
  {
    id: "sec-investing",
    section: "cashflow",
    en: "Purchases / Sales of Marketable Securities",
    ko: "유가증권 매매 (투자)",
    word: "Purchases/Sales of Securities",
    aliases: [
      "purchases of marketable securities",
      "sales of marketable securities",
      "securities investing",
      "유가증권매수",
      "유가증권매도",
    ],
    body: "여유 현금으로 국채 등을 사고파는 흐름. 금액은 커도 본업 투자와는 성격이 다릅니다. FCF에서 빼지 않는 편이 보통입니다.",
  },
  {
    id: "fcf-fin",
    section: "cashflow",
    en: "Financing Cash Flow (CFF)",
    ko: "재무활동 현금흐름",
    aliases: [
      "financing cash flow",
      "cff",
      "cash from financing",
      "total cash from financing activities",
      "재무활동현금흐름",
      "재무현금흐름",
      "재무활동 현금흐름",
    ],
    body: "차입·상환, 주식 발행, 자사주 매입, 배당. 주주·채권자와 오가는 돈입니다.",
  },
  {
    id: "debt-issued",
    section: "cashflow",
    en: "Proceeds from Borrowings / Issuance of Debt",
    ko: "차입금 조달",
    aliases: ["proceeds from borrowings", "issuance of debt", "issuance of long-term debt", "차입", "사채발행"],
    body: "새로 빌린 돈. 양수입니다. 만기 차환인지 성장 투자인지 같이 봅니다.",
  },
  {
    id: "debt-repay",
    section: "cashflow",
    en: "Repayment of Debt",
    ko: "차입금 상환",
    aliases: ["repayment of debt", "repayments of borrowings", "principal payments", "차입금상환", "사채상환"],
    body: "원금을 갚는 현금 유출. 이자 지급은 보통 영업활동에 들어갑니다(미국 GAAP).",
  },
  {
    id: "stock-issue",
    section: "cashflow",
    en: "Issuance of Common Stock / Proceeds from Stock Options",
    ko: "주식 발행 수입",
    aliases: ["issuance of common stock", "proceeds from stock options", "employee stock", "유상증자", "주식발행"],
    body: "증자나 옵션 행사로 들어온 현금. 희석의 반대편(회사로 현금 유입)입니다.",
  },
  {
    id: "buyback-cf",
    section: "cashflow",
    en: "Repurchase of Common Stock / Share Buyback",
    ko: "자사주 매입",
    aliases: [
      "repurchase of common stock",
      "share repurchase",
      "share buyback",
      "treasury stock purchases",
      "자사주매입",
      "자사주 매입",
      "자기주식취득",
    ],
    body: "시장에서 자기 주식을 사는 현금. EPS를 받치고 주주환원입니다. 고평가에 사면 자본을 낭비한 것이 됩니다.",
  },
  {
    id: "dividends-paid",
    section: "cashflow",
    en: "Dividends Paid",
    ko: "배당금 지급",
    aliases: ["dividends paid", "cash dividends", "배당금", "배당금지급", "현금배당"],
    body: "주주에게 준 현금 배당. 미국 GAAP 현금흐름표의 재무활동 유출입니다.",
  },
  {
    id: "fcf",
    section: "cashflow",
    en: "Free Cash Flow (FCF)",
    ko: "잉여현금흐름",
    aliases: ["free cash flow", "fcf", "levered free cash flow", "잉여현금흐름", "잉여 현금흐름"],
    formula: "OCF − CapEx",
    body: "본업으로 번 현금에서 설비 유지를 뺀, 배당·자사주·부채 상환에 쓸 수 있는 현금. 정의가 회사마다 조금 달라 계산 과정을 확인합니다.",
  },
  {
    id: "ufcf",
    section: "cashflow",
    en: "Unlevered Free Cash Flow (FCFF)",
    ko: "부채 반영 전 잉여현금흐름",
    aliases: ["unlevered free cash flow", "fcff", "free cash flow to firm"],
    body: "이자 효과 전, 기업 전체(주주+채권자)에 돌아가는 현금. DCF의 표준 분자입니다. FCFE는 주주 몫만입니다.",
  },
  {
    id: "fx-cash",
    section: "cashflow",
    en: "Effect of Exchange Rates on Cash",
    ko: "환율변동이 현금에 미치는 영향",
    aliases: ["effect of exchange rate", "fx on cash", "환율효과", "외화환산현금"],
    body: "해외 현금의 달러 환산 차이. 영업·투자·재무 어디에도 안 넣고 따로 한 줄로 붙습니다.",
  },
  {
    id: "net-change-cash",
    section: "cashflow",
    en: "Net Change in Cash",
    ko: "현금 증감",
    aliases: ["net change in cash", "increase in cash", "현금증감", "현금의증가"],
    formula: "OCF + ICF + CFF (+ 환율효과)",
    body: "그 기간 현금이 얼마나 늘거나 줄었는지. 기초 현금 + 이 금액 = 기말 현금(재무상태표와 일치해야 합니다).",
  },

  // —— 비율·밸류 ——
  {
    id: "per",
    section: "metrics",
    en: "P/E (PER)",
    ko: "주가수익비율",
    word: "P/E (PER)",
    aliases: ["p/e", "pe", "per", "price to earnings", "price earnings", "per (주가수익비율)", "주가수익비율"],
    formula: "주가 ÷ EPS",
    body: "이익 1달러당 주가. TTM(지난 12개월)과 Forward(예상)를 구분합니다. 일회성 이익이 있으면 왜곡됩니다.",
  },
  {
    id: "forward-per",
    section: "metrics",
    en: "Forward PER",
    ko: "예상 주가수익비율",
    aliases: ["forward per", "forward p/e", "fwd pe", "forward pe"],
    formula: "주가 ÷ 향후 12개월(또는 익년) 예상 EPS",
    body: "컨센서스 이익 기준 PER. 성장주는 TTM보다 낮게 나오는 경우가 많습니다. 예상치가 빗나가면 바로 바뀝니다.",
  },
  {
    id: "eps-metric",
    section: "metrics",
    en: "EPS",
    ko: "주당순이익",
    aliases: ["eps (주당순이익)", "forward eps", "주당순이익"],
    body: "한 주당 귀속 순이익. Forward EPS는 애널리스트 예상. PER의 분모입니다.",
  },
  {
    id: "bps",
    section: "metrics",
    en: "BPS / Book Value per Share",
    ko: "주당순자산",
    word: "BPS",
    aliases: ["bps", "book value per share", "bvps", "주당순자산", "bps (주당순자산)"],
    formula: "Shareholders' Equity ÷ Shares",
    body: "한 주당 장부 순자산. PBR의 분모입니다. 무형자산·자사주 회계에 따라 의미가 달라집니다.",
  },
  {
    id: "pbr",
    section: "metrics",
    en: "P/B (PBR)",
    ko: "주가순자산비율",
    word: "P/B (PBR)",
    aliases: ["p/b", "pb", "pbr", "price to book", "주가순자산비율", "pbr (주가순자산비율)"],
    formula: "주가 ÷ BPS",
    body: "장부가 대비 주가. 은행·지주처럼 자산이 본업인 업종에서 더 쓸모 있습니다. 1배 아래여도 자산 질이 나쁘면 쌀 수 없습니다.",
  },
  {
    id: "psr",
    section: "metrics",
    en: "P/S (PSR)",
    ko: "주가매출비율",
    word: "P/S (PSR)",
    aliases: ["p/s", "ps", "psr", "price to sales", "주가매출비율"],
    formula: "시가총액 ÷ 매출",
    body: "적자·이익 왜곡이 있을 때 쓰는 배수. 이익률이 낮은 회사는 P/S만으로 비싸 보일 수 있습니다.",
  },
  {
    id: "pcf",
    section: "metrics",
    en: "P/CF (Price to Cash Flow)",
    ko: "주가현금흐름비율",
    word: "P/CF",
    aliases: ["p/cf", "pcf", "price to cash flow", "주가현금흐름비율"],
    formula: "시가총액 ÷ 영업현금흐름",
    body: "회계 이익 대신 현금 기준 배수. 감가·운전자본 차이가 큰 회사에 보조로 씁니다.",
  },
  {
    id: "peg",
    section: "metrics",
    en: "PEG",
    ko: "PEG (성장 대비 PER)",
    aliases: ["peg", "peg ratio", "price earnings growth"],
    formula: "PER ÷ 예상 EPS 성장률(%)",
    body: "성장까지 나눈 배수. 전통적으로 1 전후를 감각으로 보지만 절대 규칙은 아닙니다. 성장률 가정이 핵심입니다.",
  },
  {
    id: "ev",
    section: "metrics",
    en: "Enterprise Value (EV)",
    ko: "기업가치",
    aliases: ["enterprise value", "ev", "기업가치"],
    formula: "시가총액 + 순부채",
    body: "주주만이 아니라 채권자 몫까지 포함한 회사 전체 가격. EV/EBITDA, EV/Sales의 분자입니다.",
  },
  {
    id: "ev-ebitda",
    section: "metrics",
    en: "EV/EBITDA",
    ko: "EV/EBITDA",
    word: "EV/EBITDA",
    aliases: ["ev/ebitda", "ev ebitda", "enterprise value to ebitda"],
    body: "자본구조가 다른 회사끼리 비교할 때 쓰는 현금이익 배수. 금융주는 잘 안 씁니다. 설비 산업에서 PER보다 덜 왜곡되는 경우가 많습니다.",
  },
  {
    id: "ev-sales",
    section: "metrics",
    en: "EV/Sales",
    ko: "EV/매출",
    word: "EV/Sales",
    aliases: ["ev/sales", "ev/revenue", "ev sales", "ev/매출"],
    body: "매출 1달러당 기업가치. 아직 이익이 안 난 성장주 비교에 씁니다.",
  },
  {
    id: "market-cap",
    section: "metrics",
    en: "Market Capitalization",
    ko: "시가총액",
    aliases: ["market cap", "market capitalization", "시가총액", "시총"],
    formula: "주가 × 유통주식 수",
    body: "주식 시장이 매긴 주주 지분 가격. EV와 달리 부채·현금을 더하거나 빼지 않습니다.",
  },
  {
    id: "div-yield",
    section: "metrics",
    en: "Dividend Yield",
    ko: "배당수익률",
    aliases: ["dividend yield", "yield", "배당수익률", "배당 수익률"],
    formula: "연간 배당금 ÷ 주가",
    body: "주가 대비 현금 배당. 높다고 무조건 좋은 게 아니라, 배당이 유지 가능한지(지급성향·FCF)를 같이 봅니다.",
  },
  {
    id: "payout",
    section: "metrics",
    en: "Dividend Payout Ratio",
    ko: "배당성향",
    aliases: ["payout ratio", "dividend payout", "배당성향", "지급성향"],
    formula: "배당금 ÷ 순이익 (또는 FCF)",
    body: "이익 중 얼마를 배당하는지. 너무 높으면 성장 투자·완충이 부족할 수 있습니다.",
  },
  {
    id: "profit-margin",
    section: "metrics",
    en: "Net Profit Margin",
    ko: "순이익률",
    aliases: ["profit margin", "net margin", "net profit margin", "순이익률", "순이익 률"],
    formula: "(Net Income ÷ Revenue) × 100",
    body: "매출 대비 최종 이익. 일회성 손익이 끼면 한 분기만 보고 판단하지 않습니다.",
  },
  {
    id: "roe",
    section: "metrics",
    en: "ROE — Return on Equity",
    ko: "자기자본이익률",
    aliases: ["roe", "return on equity", "자기자본이익률", "자기자본수익률"],
    formula: "Net Income ÷ Shareholders' Equity",
    body: "주주 자본 대비 이익. 자사주로 자본을 줄이면 올라 보일 수 있고, 부채를 많이 쓰면 레버리지로 올라갑니다. ROIC와 같이 보면 본업 수익성이 갈립니다.",
  },
  {
    id: "roa",
    section: "metrics",
    en: "ROA — Return on Assets",
    ko: "총자산이익률",
    aliases: ["roa", "return on assets", "총자산이익률"],
    formula: "Net Income ÷ Total Assets",
    body: "자산 전체를 얼마나 효율적으로 굴리는지. 은행은 자산이 커서 낮게 나오는 것이 정상입니다.",
  },
  {
    id: "roic",
    section: "metrics",
    en: "ROIC — Return on Invested Capital",
    ko: "투하자본수익률",
    aliases: ["roic", "return on invested capital", "투하자본수익률", "투하자본이익률"],
    formula: "NOPAT ÷ Invested Capital",
    body: "본업에 넣은 자본(자기자본+순부채 등) 대비 세후영업이익. 자본배분의 핵심 성적표입니다. WACC보다 높으면 가치를 창출한다고 봅니다.",
  },
  {
    id: "nopat",
    section: "metrics",
    en: "NOPAT",
    ko: "세후순영업이익",
    aliases: ["nopat", "net operating profit after tax", "세후영업이익"],
    formula: "Operating Income × (1 − tax rate)",
    body: "레버리지(이자)를 빼기 전, 본업의 세후 이익. ROIC 분자입니다.",
  },
  {
    id: "current-ratio",
    section: "metrics",
    en: "Current Ratio",
    ko: "유동비율",
    aliases: ["current ratio", "유동비율"],
    formula: "Current Assets ÷ Current Liabilities",
    body: "단기 부채를 유동자산으로 감당할 수 있는지. 업종마다 정상 구간이 다릅니다. 1 아래면 단기 유동성을 더 봅니다.",
  },
  {
    id: "quick-ratio",
    section: "metrics",
    en: "Quick Ratio / Acid Test",
    ko: "당좌비율",
    aliases: ["quick ratio", "acid test", "당좌비율"],
    formula: "(현금 + 단기투자 + 매출채권) ÷ 유동부채",
    body: "재고를 빼고 보는 더 깐깐한 단기 지급 능력. 재고가 안 팔릴 수 있는 업종에서 의미가 큽니다.",
  },
  {
    id: "dso",
    section: "metrics",
    en: "DSO — Days Sales Outstanding",
    ko: "매출채권 회수일",
    aliases: ["dso", "days sales outstanding", "receivable days", "매출채권회수일", "매출채권회전일"],
    formula: "(매출채권 ÷ 매출) × 365",
    body: "외상 회수에 걸리는 평균 일수. 늘어나면 고객 신용·독촉이 약해진 신호일 수 있습니다.",
  },
  {
    id: "dio",
    section: "metrics",
    en: "DIO — Days Inventory Outstanding",
    ko: "재고자산 회전일",
    aliases: ["dio", "days inventory outstanding", "inventory days", "재고자산회전일", "재고일수"],
    formula: "(재고 ÷ 매출원가) × 365",
    body: "재고가 팔릴 때까지 걸리는 일수. 늘면 체화·수요 둔화 가능성이 있습니다.",
  },
  {
    id: "dpo",
    section: "metrics",
    en: "DPO — Days Payable Outstanding",
    ko: "매입채무 지급일",
    aliases: ["dpo", "days payable outstanding", "payable days", "매입채무지급일"],
    formula: "(매입채무 ÷ 매출원가) × 365",
    body: "외상을 갚는 데 걸리는 일수. 길면 현금에 유리하지만, 협력사를 쥐어짜는 것일 수도 있습니다.",
  },
  {
    id: "ccc",
    section: "metrics",
    en: "Cash Conversion Cycle (CCC)",
    ko: "현금회수주기",
    aliases: ["ccc", "cash conversion cycle", "현금회수주기", "현금순환주기"],
    formula: "DSO + DIO − DPO",
    body: "현금이 재고·외상으로 나갔다가 돌아오는 기간. 짧을수록 운전자본 효율이 좋습니다. 음수면 고객·협력사 돈으로 사업을 도는 경우에 가깝습니다.",
  },
  {
    id: "interest-cover",
    section: "metrics",
    en: "Interest Coverage",
    ko: "이자보상배율",
    aliases: ["interest coverage", "times interest earned", "이자보상배율", "이자보상비율"],
    formula: "EBIT (또는 OCF) ÷ Interest Expense",
    body: "영업이익으로 이자를 몇 배 감당하는지. 낮아지면 금리·부채 부담이 커진 것입니다.",
  },
  {
    id: "de-ratio",
    section: "metrics",
    en: "Debt-to-Equity / Leverage",
    ko: "부채비율",
    word: "D/E",
    aliases: ["debt to equity", "d/e", "leverage", "부채비율", "부채자본비율"],
    formula: "총부채 ÷ 자본 (또는 총차입 ÷ 자본)",
    body: "레버리지. 정의(총부채 vs 이자부부채)가 자료마다 달라 분자를 확인합니다.",
  },
  {
    id: "fcf-yield",
    section: "metrics",
    en: "FCF Yield",
    ko: "잉여현금 수익률",
    aliases: ["fcf yield", "free cash flow yield", "잉여현금수익률"],
    formula: "FCF ÷ 시가총액",
    body: "주가가 현금창출력 대비 얼마나 싼지. PER의 현금 버전 감각입니다.",
  },
  {
    id: "dilution-rate",
    section: "metrics",
    en: "Share Dilution Rate",
    ko: "주식 희석률",
    aliases: ["dilution", "share dilution", "dilution rate", "희석률", "주식희석"],
    body: "SBC·전환으로 주식 수가 늘어나는 속도. 자사주가 희석을 상쇄하는지 같이 봅니다. EPS 성장의 숨은 변수입니다.",
  },

  // —— 읽는 법·약어 ——
  {
    id: "gaap",
    section: "reading",
    en: "GAAP (US GAAP)",
    ko: "미국 일반기업회계기준",
    aliases: ["gaap", "us gaap", "accounting principles", "미국gaap"],
    body: "SEC 보고서의 공식 숫자 기준. IFRS와 리스·R&D 등에서 차이가 있습니다. 10-K/10-Q 본표는 GAAP입니다.",
  },
  {
    id: "ifrs",
    section: "reading",
    en: "IFRS",
    ko: "국제회계기준",
    aliases: ["ifrs", "international financial reporting standards"],
    body: "많은 해외 기업(20-F)이 쓰는 기준. 미국 상장 외국기업은 IFRS 또는 US GAAP로 보고합니다.",
  },
  {
    id: "accrual",
    section: "reading",
    en: "Accrual Accounting",
    ko: "발생주의",
    aliases: ["accrual", "accrual accounting", "발생주의"],
    body: "현금이 오간 때가 아니라, 수익·비용을 ‘발생’한 기간에 인식. 그래서 순이익과 현금흐름이 다릅니다.",
  },
  {
    id: "revenue-rec",
    section: "reading",
    en: "Revenue Recognition (ASC 606)",
    ko: "수익인식 기준",
    aliases: ["revenue recognition", "asc 606", "asc606", "수익인식"],
    body: "고객과의 계약을 수행의무로 나눠, 통제가 넘어간 시점에 매출을 인식. 구독·라이선스·다년 계약은 이연수익과 세트로 봅니다.",
  },
  {
    id: "yoy",
    section: "reading",
    en: "YoY — Year over Year",
    ko: "전년 동기 대비",
    aliases: ["yoy", "year over year", "year-over-year", "전년대비", "전년 동기", "전년 대비"],
    body: "작년 같은 기간과 비교. 계절성을 걸러 성장 속도를 봅니다. 이 앱 재무제표 표의 ‘전년 대비’ 열입니다.",
  },
  {
    id: "qoq",
    section: "reading",
    en: "QoQ — Quarter over Quarter",
    ko: "전분기 대비",
    aliases: ["qoq", "quarter over quarter", "전분기대비", "이전 발표 대비"],
    body: "직전 분기와 비교. 계절성(연말 쇼핑, 세금 시즌)이 커서 YoY와 같이 봐야 합니다.",
  },
  {
    id: "ttm",
    section: "reading",
    en: "TTM / LTM — Trailing Twelve Months",
    ko: "최근 12개월",
    aliases: ["ttm", "ltm", "trailing twelve months", "last twelve months", "최근12개월", "연환산"],
    body: "최근 4개 분기를 더한 실적. 연간 보고서가 오래됐을 때 PER·마진의 표준 분모로 씁니다.",
  },
  {
    id: "ntm",
    section: "reading",
    en: "NTM — Next Twelve Months",
    ko: "향후 12개월",
    aliases: ["ntm", "next twelve months", "fwd", "forward", "향후12개월"],
    body: "앞으로 12개월 예상치. Forward PER의 분모로 자주 씁니다.",
  },
  {
    id: "fy-q",
    section: "reading",
    en: "FY / FQ / Calendar vs Fiscal",
    ko: "회계연도·회계분기",
    aliases: ["fy", "fiscal year", "fiscal quarter", "fq", "calendar year", "회계연도", "회계분기", "결산월"],
    body: "FY는 회계연도. 애플처럼 9월 결산이면 FY2025가 2024년 가을~2025년 가을입니다. 달력연도(Calendar)와 섞어 읽지 않습니다.",
  },
  {
    id: "beat-miss",
    section: "reading",
    en: "Beat / Miss / Consensus",
    ko: "컨센서스 대비 초과·미달",
    aliases: ["beat", "miss", "consensus", "whisper", "컨센서스", "예상치", "서프라이즈"],
    body: "애널리스트 평균 예상(컨센서스)보다 실제가 좋으면 Beat, 못 미치면 Miss. 매출 Beat인데 EPS Miss처럼 따로 봅니다.",
  },
  {
    id: "guidance",
    section: "reading",
    en: "Guidance / Outlook",
    ko: "가이던스",
    aliases: ["guidance", "outlook", "forecast", "가이던스", "전망", "실적가이던스"],
    body: "회사가 앞으로의 매출·이익 범위를 스스로 제시. 없는 회사(버크셔 등)는 컨센서스로 대체합니다. 실적 당일 주가는 가이던스에 더 반응하는 경우가 많습니다.",
  },
  {
    id: "mda",
    section: "reading",
    en: "MD&A — Management's Discussion & Analysis",
    ko: "경영진 토론 및 분석",
    aliases: ["md&a", "mda", "management discussion", "item 7", "경영진토론", "mdna"],
    body: "10-K/10-Q에서 경영진이 숫자 변동 이유, 리스크, 유동성, 전망을 글로 설명하는 핵심 섹션. 표만 보지 말고 여기의 P(가격) vs Q(물량) 설명을 봅니다.",
  },
  {
    id: "notes",
    section: "reading",
    en: "Notes to Financial Statements",
    ko: "재무제표 주석",
    aliases: ["notes", "footnotes", "notes to financial statements", "주석", "재무제표주석"],
    body: "회계정책, 부문별 실적, 부채 만기, 소송, 리스, 수익 내역 등 표에 안 보이는 디테일. 숫자 해석의 본문입니다.",
  },
  {
    id: "segment",
    section: "reading",
    en: "Segment Reporting",
    ko: "부문별 공시",
    aliases: ["segment", "reportable segment", "부문", "사업부문", "세그먼트"],
    body: "제품군·지역별 매출·이익. 전체 합계만 보면 성장 사업과 사양 사업이 섞입니다. 주석에 있습니다.",
  },
  {
    id: "material",
    section: "reading",
    en: "Material / Materiality",
    ko: "중요성",
    aliases: ["material", "materiality", "material weakness", "중요성", "중요취약점"],
    body: "투자 판단에 영향을 줄 만한 크기. Material weakness는 내부통제가 재무 오류를 막기 어렵다는 심각한 지적입니다.",
  },
  {
    id: "going-concern",
    section: "reading",
    en: "Going Concern",
    ko: "계속기업 가정",
    aliases: ["going concern", "계속기업"],
    body: "회사가 가까운 미래에 영업을 계속할 수 있다는 전제. 감사의견에 의문이 붙으면 생존 리스크 경고입니다.",
  },
  {
    id: "off-bs",
    section: "reading",
    en: "Off-balance-sheet",
    ko: "부외 항목",
    aliases: ["off-balance-sheet", "off balance sheet", "부외", "난외"],
    body: "표에 자산·부채로 안 올라간 의무(일부 보증, 약정). 주석의 commitments를 봐야 합니다. 리스는 이제는 대부분 표에 올라갑니다.",
  },
  {
    id: "fair-value",
    section: "reading",
    en: "Fair Value Hierarchy (Level 1 / 2 / 3)",
    ko: "공정가치 서열",
    aliases: ["fair value", "level 1", "level 2", "level 3", "공정가치", "레벨3"],
    body: "Level 1은 상장 시세, 2는 관측 가능한 투입, 3은 모델·가정. Level 3 비중이 크면 평가가 주관적입니다.",
  },
  {
    id: "asc-842",
    section: "reading",
    en: "ASC 842 — Leases",
    ko: "리스 회계",
    aliases: ["asc 842", "asc842", "lease accounting", "리스회계"],
    body: "운용리스도 사용권자산·리스부채로 올리는 기준. 총자산·총부채가 예전보다 커 보입니다.",
  },
  {
    id: "cecl",
    section: "reading",
    en: "CECL",
    ko: "현재예상신용손실",
    aliases: ["cecl", "current expected credit losses", "현재예상신용손실"],
    body: "은행이 대출 손실을 ‘이미 발생한 것만’이 아니라 전 기간 기대로 미리 쌓는 기준. 경기 전망이 충당금을 크게 움직입니다.",
  },
  {
    id: "xbrl",
    section: "reading",
    en: "XBRL",
    ko: "재무제표 전자공시 태그",
    aliases: ["xbrl", "ixbrl"],
    body: "SEC 숫자에 붙는 기계가독 태그. EDGAR에서 표 데이터를 추출하는 기반입니다.",
  },
  {
    id: "audit",
    section: "reading",
    en: "Audit Opinion / Unqualified",
    ko: "감사의견",
    aliases: ["audit", "unqualified", "qualified opinion", "감사의견", "적정의견"],
    body: "10-K 재무제표는 감사받습니다. Unqualified(적정)가 일반적입니다. 10-Q는 검토(review)만 받아 감사보다 얕습니다.",
  },
  {
    id: "restatement",
    section: "reading",
    en: "Restatement",
    ko: "재무제표 재작성",
    aliases: ["restatement", "restate", "재작성", "소급수정"],
    body: "과거 숫자를 오류로 다시 쓰는 것. 가벼운 재분류와 달리 신뢰도 타격이 큽니다. 10-K/A와 함께 봅니다.",
  },
  {
    id: "non-gaap-reconciliation",
    section: "reading",
    en: "GAAP to Non-GAAP Reconciliation",
    ko: "GAAP↔조정실적 조정표",
    aliases: ["reconciliation", "gaap reconciliation", "조정표"],
    body: "조정 EPS가 있을 때 반드시 있는 다리. 무엇을 뺐는지(SBC, 상각, 구조조정) 여기서 확인합니다.",
  },
  {
    id: "item-1a",
    section: "reading",
    en: "Item 1A — Risk Factors",
    ko: "위험요인",
    aliases: ["item 1a", "risk factors", "위험요인", "리스크요인"],
    body: "10-K에 회사가 적는 사업·재무·소송·공급망 리스크. 상투적이어도 새로 길어진 항목은 경영진이 최근 걱정하는 부분입니다.",
  },
  {
    id: "capital-allocation",
    section: "reading",
    en: "Capital Allocation",
    ko: "자본배분",
    aliases: ["capital allocation", "capital return", "주주환원", "자본배분"],
    body: "번 현금을 재투자·M&A·부채 상환·배당·자사주에 나누는 방식. ROIC, 희석, 순부채와 같이 평가합니다.",
  },

  // —— SEC 공시 ——
  {
    id: "edgar",
    section: "sec",
    en: "EDGAR",
    ko: "SEC 전자공시 시스템",
    aliases: ["edgar", "sec.gov", "sec edgar"],
    body: "sec.gov/edgar에서 티커로 10-K, 10-Q, 8-K, Form 4, 13F 등 모든 공시를 조회합니다.",
  },
  {
    id: "10k",
    section: "sec",
    en: "Form 10-K",
    ko: "연간 사업보고서",
    aliases: ["10-k", "10k", "form 10-k", "annual report"],
    body: "미국 국내 상장사의 연간 보고서. 감사받은 재무제표, MD&A, 리스크(Item 1A), 내부통제. 회계연도 종료 후 대형 가속신고인 60일·가속 75일·그 외 90일.",
  },
  {
    id: "10q",
    section: "sec",
    en: "Form 10-Q",
    ko: "분기 보고서",
    aliases: ["10-q", "10q", "form 10-q", "quarterly report"],
    body: "1·2·3분기 보고서(4분기는 10-K). 미감사 요약 재무제표와 최신 MD&A. 분기 종료 후 40~45일.",
  },
  {
    id: "20f",
    section: "sec",
    en: "Form 20-F",
    ko: "외국기업 연간보고서",
    aliases: ["20-f", "20f", "form 20-f"],
    body: "ADR 등으로 미국 상장한 해외 기업(쿠팡, TSMC 등)의 연간 보고서. 회계연도 종료 후 4개월 이내. 10-K에 해당합니다.",
  },
  {
    id: "6k",
    section: "sec",
    en: "Form 6-K",
    ko: "외국기업 수시보고서",
    aliases: ["6-k", "6k", "form 6-k"],
    body: "해외 기업이 본국 공시·실적을 SEC에 제출하는 수시 서류. 실적 발표가 여기로 오기도 합니다.",
  },
  {
    id: "8k",
    section: "sec",
    en: "Form 8-K",
    ko: "수시 공시 (중요 사건)",
    aliases: ["8-k", "8k", "form 8-k", "current report"],
    body: "M&A, 경영진 교체, 실적 프리뷰, 파산, 회계법인 변경, 주총 결과 등. 중대 사건 후 4영업일. 실적 당일 8-K + 실적자료가 먼저 나옵니다.",
  },
  {
    id: "s1",
    section: "sec",
    en: "Form S-1 / F-1",
    ko: "증권신고서 (IPO)",
    aliases: ["s-1", "s1", "f-1", "f1", "form s-1", "ipo filing"],
    body: "미국 기업 IPO는 S-1, 외국 기업은 F-1. 사업·위험·재무가 가장 두껍게 나옵니다.",
  },
  {
    id: "s3",
    section: "sec",
    en: "Form S-3",
    ko: "간이 증권신고서",
    aliases: ["s-3", "s3", "form s-3", "shelf registration"],
    body: "이미 상장된 우량 기업이 유상증자·회사채·워런트를 빠르게 등록. Shelf(선등록)로 두고 필요할 때 발행하기도 합니다.",
  },
  {
    id: "s8",
    section: "sec",
    en: "Form S-8",
    ko: "임직원 주식보상 신고서",
    aliases: ["s-8", "s8", "form s-8"],
    body: "스톡옵션·RSU·ESPP용 주식을 등록. 희석의 공급 파이프라인입니다.",
  },
  {
    id: "form3",
    section: "sec",
    en: "Form 3",
    ko: "내부자 최초 지분 공시",
    aliases: ["form 3", "form3"],
    body: "임원·이사·10% 대주주가 된 뒤 10일 이내 보유 현황 등록.",
  },
  {
    id: "form4",
    section: "sec",
    en: "Form 4",
    ko: "내부자 지분 변동",
    aliases: ["form 4", "form4", "insider transaction"],
    body: "내부자의 매수·매도·옵션 행사. 거래일로부터 2영업일. 오픈마켓 매수는 자신감 신호로 자주 봅니다. 자동 매도(10b5-1)와 구분합니다.",
  },
  {
    id: "form5",
    section: "sec",
    en: "Form 5",
    ko: "내부자 연간 지분 변동",
    aliases: ["form 5", "form5"],
    body: "Form 4에서 빠진 소액·증여·상속 등을 회계연도 종료 후 45일 이내 보고.",
  },
  {
    id: "form144",
    section: "sec",
    en: "Form 144",
    ko: "제한주식 매도 의향",
    aliases: ["form 144", "rule 144", "144"],
    body: "제한·지배 주식을 브로커로 팔기 전 사전 통지. 실제 매도와 Form 4를 같이 봅니다.",
  },
  {
    id: "13d",
    section: "sec",
    en: "Schedule 13D",
    ko: "5% 지분 (경영 참여)",
    aliases: ["13d", "schedule 13d", "beneficial ownership"],
    body: "의결권 5% 이상을 경영 참여 목적으로 취득하면 10일 이내. 행동주의 펀드의 출현 신호로 봅니다.",
  },
  {
    id: "13g",
    section: "sec",
    en: "Schedule 13G",
    ko: "5% 지분 (단순 투자)",
    aliases: ["13g", "schedule 13g"],
    body: "5% 이상이지만 경영 참여 의사가 없는 패시브 기관이 제출. 13D보다 느슨합니다.",
  },
  {
    id: "13f",
    section: "sec",
    en: "Form 13F",
    ko: "기관 보유주식 보고",
    aliases: ["13f", "form 13f", "13f filing"],
    body: "운용자산 1억 달러 이상 매니저의 분기 포트폴리오. 분기 종료 후 45일. 45일 시차가 있어 ‘지금’이 아닙니다.",
  },
  {
    id: "def14a",
    section: "sec",
    en: "DEF 14A — Proxy Statement",
    ko: "위임장 설명서",
    aliases: ["def 14a", "def14a", "proxy", "proxy statement"],
    body: "주총 안건, 이사 선임, CEO 보상(연봉·스톡), 주주 제안. 보상 과다·이사회 독립성을 볼 때 필수입니다.",
  },
  {
    id: "pre14a",
    section: "sec",
    en: "PRE 14A / DEFA14A",
    ko: "예비·추가 위임장",
    word: "PRE 14A / DEFA14A",
    aliases: ["pre 14a", "pre14a", "defa14a", "defa 14a"],
    body: "PRE 14A는 SEC에 미리 내는 초안, DEFA14A는 주총 관련 추가 설명·홍보 자료입니다.",
  },
  {
    id: "amendment",
    section: "sec",
    en: "10-K/A · 10-Q/A",
    ko: "정정 보고서",
    aliases: ["10-k/a", "10-q/a", "amendment", "정정", "정정보고서"],
    body: "이미 낸 10-K/10-Q의 오류·누락을 고친 서류. 숫자의 신뢰도를 다시 봐야 합니다.",
  },
  {
    id: "nt10k",
    section: "sec",
    en: "Form NT 10-K / NT 10-Q",
    ko: "제출 연기 신청",
    word: "NT 10-K / NT 10-Q",
    aliases: ["nt 10-k", "nt 10-q", "nt10k", "nt10q", "late filing"],
    body: "기한 내 제출이 어려울 때 사유를 적는 서류. 회계 문제·내부통제 이슈의 경고등이 될 수 있습니다.",
  },
  {
    id: "form-sd",
    section: "sec",
    en: "Form SD",
    ko: "분쟁광물 공시",
    aliases: ["form sd", "conflict minerals", "분쟁광물"],
    body: "공급망에서 분쟁 지역 광물 사용 여부를 밝히는 ESG 공시입니다.",
  },
  {
    id: "10k-items",
    section: "sec",
    en: "10-K Item 1 / 7 / 8",
    ko: "10-K 주요 항목",
    word: "10-K Item 1·7·8",
    aliases: ["item 1", "item 7", "item 8", "business", "financial statements"],
    body: "Item 1 사업 내용, Item 7 MD&A, Item 8 감사 재무제표·주석. 숫자만 볼 때 8, 해석은 7입니다.",
  },
];

export function normalizeGlossaryKey(raw: string): string {
  return String(raw ?? "")
    .toLowerCase()
    .replace(/['’`]/g, "")
    .replace(/&/g, "and")
    .replace(/[·•]/g, "")
    .replace(/[^a-z0-9가-힣]/g, "");
}

const EXACT_INDEX = new Map<string, GlossaryEntry>();
const ALIAS_BY_LEN: { key: string; entry: GlossaryEntry }[] = [];

for (const entry of US_FINANCIAL_GLOSSARY) {
  const keys = [entry.en, entry.ko, ...entry.aliases];
  for (const raw of keys) {
    const key = normalizeGlossaryKey(raw);
    if (!key) continue;
    if (!EXACT_INDEX.has(key)) EXACT_INDEX.set(key, entry);
    ALIAS_BY_LEN.push({ key, entry });
  }
}

ALIAS_BY_LEN.sort((a, b) => b.key.length - a.key.length);

export function lookupFinancialGlossary(raw: string): GlossaryEntry | null {
  const key = normalizeGlossaryKey(raw);
  if (!key) return null;
  const exact = EXACT_INDEX.get(key);
  if (exact) return exact;
  for (const row of ALIAS_BY_LEN) {
    if (row.key.length < 4) continue;
    if (key.includes(row.key)) return row.entry;
  }
  return null;
}

export function searchFinancialGlossary(
  query: string,
  section: GlossarySectionId | "all" = "all",
): GlossaryEntry[] {
  const q = normalizeGlossaryKey(query);
  return US_FINANCIAL_GLOSSARY.filter((entry) => {
    if (section !== "all" && entry.section !== section) return false;
    if (!q) return true;
    const blob = normalizeGlossaryKey(
      `${entry.en} ${entry.ko} ${entry.aliases.join(" ")} ${entry.body} ${entry.formula ?? ""}`,
    );
    return blob.includes(q);
  });
}

export function glossarySectionLabel(id: GlossarySectionId): string {
  return GLOSSARY_SECTIONS.find((s) => s.id === id)?.label ?? id;
}
