/** Auto-generated by scripts/gen-ko-i18n.mjs — do not edit by hand */
export const ko = {
  app: {
    title: "종목 대시보드",
    subtitle: "국내 300 · 나스닥 500",
    telegram: "텔레그램",
    telegramResetAria: "오늘 텔레그램 알림 이력 초기화",
    telegramResetLabel: "알림 초기화",
    mainNav: "메인 메뉴",
    themeToggleAria: "화면 테마 전환",
    themeUseLight: "라이트 모드",
    themeUseDark: "다크 모드",
    tabScreener: "스크리너",
    tabBullish: "상승 유망",
    tabCrypto: "코인",
    rescanning: "요청 중…",
    rescan: "전체 재분석",
    nextRescanSoon: "곧 시작",
    retry: "다시 시도",
    marketKr: "국내",
    marketUs: "미국",
    bullishHint: "골든크로스·일목·정배열 등 상승 신호가 강한 종목",
    reason: "이유",
    reasonSuffix: "로 근거 확인",
    selectTitle: "종목을 선택하세요",
    selectDesc: "왼쪽 목록에서 종목을 누르면 차트가 표시됩니다",
    chartLoading: "차트 데이터를 불러오는 중",
    chartEmpty: "표시할 캔들이 없습니다.",
    cacheTag: "캐시",
    candleSuffix: "봉",
    chipMa: "이평(일)",
    chipIch: "일목",
    chipVol: "거래량",
    chipRsi: "RSI",
    failBtnTitle: "조회 실패 종목 목록",
    telegramConfirm: "오늘 발송한 텔레그램 알림 이력을 초기화할까요?\n같은 종목이 다시 점수 조건을 만족하면 알림이 재전송됩니다.",
    telegramResetFail: "알림 이력 초기화에 실패했습니다.",
    telegramListAria: "오늘 발송한 텔레그램 알림 종목 조회",
    telegramListTitle: "텔레그램 알림 이력",
    telegramListLoadFail: "알림 이력을 불러오지 못했습니다.",
    profitModelBtn: "수익 모델",
    profitModelTitle: "가정 매수가",
    profitModelHint: "설정한 가격에 1주를 매수했다고 가정할 때, 현재 시세 기준 수익률입니다. 시세는 주기적으로 갱신됩니다.",
    profitModelEntry: "매수가",
    profitModelPlaceholder: "예: 70000",
    profitModelUseQuote: "현재가 적용",
    profitModelApply: "적용",
    profitModelCancel: "취소",
    profitModelClear: "매수가 해제",
    profitModelClose: "닫기",
    profitModelReturn: "수익률",
    profitModelPerShare: "주당 손익",
    profitModelCurrentRef: "현재 시세 참고",
    profitModelStripCurrent: "현재가",
    profitModelPersistHint: "데이터는 이 브라우저에 저장되어 탭을 닫아도 유지됩니다. 다른 PC·브라우저와는 공유되지 않으며, 계정 로그인은 지원하지 않습니다.",
    profitModelBrowserId: "이 브라우저 ID",
  },
  macro: {
    title: "주요 지표 발표",
    subtitle: "남은 시간 기준 (KST)",
    live: "진행 중",
    soon: "곧 발표",
    loading: "일정 불러오는 중…",
    empty: "예정된 발표가 없습니다.",
    regionUs: "US",
    regionKr: "KR",
    guideWhat: "이 지표는?",
    guideHigh: "예상보다 높을 때",
    guideLow: "예상보다 낮을 때",
    guideNote: "참고",
    guideClose: "닫기",
    cardHint: "클릭하면 설명",
  },
  errors: {
    picksLoad: "종목 목록을 불러올 수 없습니다.",
    chartLoad: "차트를 불러올 수 없습니다.",
    newsLoad: "뉴스를 불러올 수 없습니다.",
    network: "서버에 연결할 수 없습니다. 터미널에서 npm run dev 가 실행 중인지 확인하세요.",
    parse: "서버 응답을 읽을 수 없습니다.",
    request: "요청에 실패했습니다.",
  },
  screenFailures: {
    title: "조회 실패 종목",
    sub: "총 {n}건 · Yahoo 차트 데이터를 가져오지 못한 종목",
    empty: "실패 내역이 없습니다.",
    kr: "국내",
    us: "미국",
    close: "닫기",
  },
  telegramSent: {
    title: "텔레그램 알림 이력",
    sub: "오늘 발송 · 총 {n}건",
    empty: "오늘 발송한 알림이 없습니다.",
    loading: "이력 불러오는 중…",
    kr: "국내",
    us: "미국",
    close: "닫기",
    scoreSuffix: "점",
  },
  feedback: {
    cornerButton: "불편",
    cornerAria: "불편 접수",
    menuSubmit: "내용 접수",
    menuInbox: "접수함 확인",
    submitTitle: "불편 접수",
    submitPlaceholder: "불편 사항을 적어 주세요…",
    submitSend: "보내기",
    submitOk: "접수되었습니다.",
    submitClose: "닫기",
    inboxTitle: "불편 접수함",
    inboxPasswordLabel: "비밀번호",
    inboxPasswordPlaceholder: "접수함 비밀번호",
    inboxUnlock: "확인",
    inboxReload: "새로고침",
    inboxLock: "잠금",
    inboxClose: "닫기",
    inboxEmpty: "접수된 내용이 없습니다.",
    inboxIp: "IP",
    inboxTime: "시각",
    inboxMsg: "내용",
    inboxUa: "UA",
    inboxHintNoServer: "서버에 FEEDBACK_INBOX_TOKEN이 없으면 접수함을 열 수 없습니다.",
  },
  crypto: {
    panelTitle: "주요 코인 (Binance USDT · 24h 거래량 순)",
    listAria: "코인 선택",
    listVolShort: "거래량",
    listVolTitle: "24h USDT 거래대금 (내림차순 정렬)",
    drawToolbarAria: "차트 드로잉 도구",
    drawPersistHint: "드로잉은 이 브라우저에만 저장됩니다(종목·타임프레임별). 다른 기기와는 공유되지 않습니다.",
    drawCursor: "커서",
    drawHLine: "수평선",
    drawTrend: "추세선",
    drawClear: "전체 삭제",
    chartEngineTv: "TradingView",
    chartEngineApp: "앱 차트 (지표·미니 드로잉)",
    tvCopyrightSuffix: " by TradingView",
    tvChartAria: "TradingView 임베드 차트",
  },
  access: {
    checking: "접근 권한을 확인하는 중…",
    openingApp: "서비스 화면을 여는 중…",
    statusFetchFail: "접근 권한을 확인할 수 없습니다. 서버가 실행 중인지·주소가 맞는지 확인한 뒤 다시 시도해 주세요.",
    gateTitle: "접근 제한",
    gateBody: "",
    yourIp: "",
    statePending: "",
    stateRejected: "",
    stateNone: "",
    messageLabel: "메모 (선택)",
    messagePlaceholder: "신청 사유, 연락처 등",
    submitRequest: "접속 신청",
    submitting: "전송 중…",
    adminTitle: "IP 접근 관리",
    adminConsoleTitle: "관리자",
    adminToolbarBtn: "관리자",
    adminTabAccess: "IP 접근",
    adminTabFeedback: "불편 접수함",
    adminTabTelegram: "텔레그램",
    adminTabListAria: "관리자 메뉴",
    adminTelegramOpenList: "발송 목록",
    adminPasswordLabel: "관리자 비밀번호",
    adminConfirm: "확인",
    adminLockAgain: "잠금",
    adminWrongPassword: "비밀번호가 올바르지 않습니다.",
    adminDeviceInfo: "기기·환경",
    adminTokenPlaceholder: "비밀번호 입력",
    adminSaveToken: "확인",
    adminLoad: "목록 새로고침",
    adminPending: "대기 중인 신청",
    adminAllowed: "허용된 IP",
    adminApprove: "승인",
    adminReject: "거절",
    adminRevoke: "허가 취소",
    adminClose: "닫기",
    adminEmptyPending: "대기 중인 신청이 없습니다.",
    adminEmptyAllowed: "허용된 IP가 없습니다.",
    adminUa: "User-Agent",
    adminRequestedAt: "신청 시각",
    adminError: "요청에 실패했습니다.",
    adminMemoLabel: "내 메모 (누구·용도)",
    adminMemoPlaceholder: "예: 홍길동 노트북, 사무실 PC",
    adminMemoSave: "메모 저장",
    adminRequestMessage: "신청 메시지",
    requestDeviceNote: "",
  },
  launch: {
    loading: "불러오는 중…",
  },
} as const;

export const macroGuide = {
  CPI: {
    what: "소비자가 사는 물가의 상승 평균을 나타낸 지표입니다. 흔히 말하는 ‘인플레이션’의 대표 숫자입니다.",
    high: "물가 상승이 예상보다 큽니다. 금리 인상·긴축 우려가 커져 주식·채권·성장주에 부담이 될 수 있고, 달러·원화 약세(환율↑) 방향으로 움직이는 경우가 많습니다.",
    low: "물가 상승이 예상보다 작습니다. 금리 인하·완화 기대가 커져 성장주·기술주·채권 가격에 우호적인 반응이 나올 수 있습니다.",
  },
  PPI: {
    what: "기업이 물건을 살 때 부담하는 원가(생산자 물가)입니다. 소비자 물가(CPI) 발표 전 물가 흐름을 보는 선행 지표입니다.",
    high: "원가 상승이 큽다는 뜻은 곧 소비자 물가도 오를 수 있다는 신호입니다. 금리 인상 우려·기업 마진 압박으로 주식에 부담이 될 수 있습니다.",
    low: "원가 압력이 예상보다 약합니다. 인플 둔화·금리 완화 기대가 커져 성장주에 우호적일 수 있습니다.",
  },
  NFP: {
    what: "미국 비농업 부문에서 전월 비해 얼마나 고용이 늘었는지 보는 지표입니다. 경기 체감을 가장 직접적으로 보는 숫자입니다.",
    high: "고용이 예상보다 많이 늘었습니다. 경기가 강하다는 인식이지만, 금리 인상·달러 강세 우려로 단기적으로 주식 변동성이 커질 수 있습니다.",
    low: "고용이 예상보다 적게 늘었거나 줄었습니다. 경기 둔화 우려·금리 인하 기대가 커져 성장주·기술주·리스크 자산에 우호적일 수 있습니다.",
  },
  FOMC: {
    what: "미 연준이 금리를 올릴지 내릴지 결정하는 회의입니다. 시장은 숫자보다 ‘앞으로 어떻게 갈 것인지’를 더 많이 봅니다.",
    high: "금리를 올리거나 더 오래 긴축할 것이라는 심리가 강합니다(매파적). 주식·채권 압력, 고수익·성장주에 부담, 은행·채권에는 상대적 우호가 나올 수 있습니다.",
    low: "금리를 내리거나 완화를 유지할 것이라는 심리가 강합니다(비둔화). 성장주·기술주·부동산에 우호적인 반응이 나올 수 있습니다.",
    note: "예상보다 ‘높다/낮다’보다, 실제 금리 변동 여부와 회의 톤이 더 중요합니다.",
  },
  FOMC_MINUTES: {
    what: "지난 FOMC 회의에서 어떤 이야기가 나왔는지 기록한 자료입니다. 금리 결정 이후 시장 심리를 읽는 용도입니다.",
    high: "인플 우려·금리 인상을 강조하는 내용이 많을 때(매파 톤). 주식 압력, 금리↑ 기대가 살아날 수 있습니다.",
    low: "경기 둔화·금리 완화를 강조하는 내용이 많을 때(비둔화 톤). 성장주·채권에 우호적일 수 있습니다.",
    note: "발표 직후 변동성은 정식 FOMC보다 작은 경우가 많습니다.",
  },
  GDP: {
    what: "미국 경제가 이전 분기 대비 얼마나 성장했는지 보는 지표입니다. 경제 활력의 바오미터입니다.",
    high: "성장률이 예상보다 높습니다. 경기 확장 기대로 주식·원자재·산업주에 우호적일 수 있습니다.",
    low: "성장률이 예상보다 낮습니다. 경기 둔화 우려·금리 인하 기대가 커져 방어적 자산이 강조될 수 있습니다.",
    note: "최종 수치는 발표 직후 재고 수정에 따라 반응이 달라질 수 있습니다.",
  },
  PCE: {
    what: "연준이 물가 안정을 판단할 때 가장 중요하게 보는 미국 인플 지표입니다. 소비자가 실제 지출한 물가 흐름을 추적합니다.",
    high: "물가 상승이 예상보다 큽니다. CPI와 비슷하게 금리 인상 우려·주식 압력이 커질 수 있습니다.",
    low: "물가 상승이 예상보다 작습니다. 인플 둔화·금리 완화 기대가 커져 성장주에 우호적일 수 있습니다.",
  },
  RETAIL: {
    what: "소비자가 매장에서 얼마나 샀는지 보는 지표입니다. 실제 수요가 경기와 함께 움직이는지 보는 선행 지표입니다.",
    high: "소비가 예상보다 활발합니다. 경기 확장 기대로 소비주·자율주·성장주에 우호적일 수 있습니다.",
    low: "소비가 예상보다 부진합니다. 경기 둔화 우려가 커져 주식 전반에 부담이 될 수 있습니다.",
  },
  ISM_MFG: {
    what: "제조업 경기 선행 지수(PMI)입니다. 50을 기준으로 50 이상이면 확장, 미만이면 위축 구간으로 봅니다.",
    high: "지수가 예상보다 높거나 50 이상입니다. 제조업·원자재·산업주에 우호적이나, 경기가 과열되면 금리 인상 우려도 함께 따를 수 있습니다.",
    low: "지수가 예상보다 낮거나 50 미만입니다. 경기 둔화 우려가 커져 주식 전반에 부담이 될 수 있습니다.",
    note: "기술주에는 직접 영향이 제한적이고, 전체 시장 심리에 영향을 줍니다.",
  },
  ISM_SVC: {
    what: "서비스 업종 경기 선행 PMI입니다. 미국 경제의 대부분을 차지하는 부문이라 중요도가 높습니다.",
    high: "서비스 경기가 예상보다 좋습니다. 경기 확장 기대가 커지지만, 금리 인상 우려로 주식 변동성이 커질 수 있습니다.",
    low: "서비스 경기가 예상보다 약합니다. 경기 둔화·금리 완화 기대로 방어적 자산에 우호적일 수 있습니다.",
  },
  JOBLESS: {
    what: "주간 실업 수당 신청 건수입니다. 고용 시장이 지금 당장 어떤지 보는 즉시성 지표입니다.",
    high: "신청 건수가 예상보다 많습니다(실업 주변이 더 안 좋아지는 상황). 경기 둔화·금리 인하 기대로 주식에 부담이 될 수 있습니다.",
    low: "신청 건수가 예상보다 적습니다(고용 시장 개선). 주식에 우호적이며, NFP 발표 전 심리 요인으로도 봅니다.",
    note: "이 지표는 높을수록 ‘좋은 소식’이 아닙니다. 다른 지표와 반대로 읽으세요.",
  },
  JOLTS: {
    what: "기업이 올리는 구인 공고 수입니다. 채용 수요가 얼마나 활발한지 보는 지표입니다.",
    high: "구인 공고가 예상보다 많습니다. 고용 시장이 뜨겁지만, 금리 인상 우려로 단기 주식 변동성이 커질 수 있습니다.",
    low: "구인 공고가 예상보다 적습니다. 채용 둔화·금리 완화 기대가 커져 성장주에 우호적일 수 있습니다.",
  },
  CONSUMER_CONF: {
    what: "소비자가 앞으로 경제를 어떻게 볼지 조사한 심리 지수입니다. 소비 지출의 선행 지표입니다.",
    high: "소비 심리가 예상보다 좋습니다. 앞으로 소비·성장이 늘 것으로 보여 성장주·자율주에 우호적일 수 있습니다.",
    low: "소비 심리가 예상보다 나쁩니다. 소비 둔화 우려가 커져 방어적 자산이 강조될 수 있습니다.",
  },
  ADP: {
    what: "미국 사립 기업 고용 변화를 조사한 지표입니다. 공식 고용 지표(NFP) 발표 전 시장이 보는 선행 신호입니다.",
    high: "고용 증가가 예상보다 큽니다. NFP도 강할 것으로 예상되어 금리 인상 우려·주식 변동성이 커질 수 있습니다.",
    low: "고용 증가가 예상보다 작습니다. NFP 부진·금리 완화 기대로 성장주에 우호적일 수 있습니다.",
  },
  KR_CPI: {
    what: "한국 소비자물가 지수입니다. 원/달러 환율과 한국은행 금리 정책에 직접 영향을 줍니다.",
    high: "물가 상승이 예상보다 큽니다. 금리 인상·원화 약세(환율↑)로 수출주는 상대적 우호, 내수·성장주는 부담이 될 수 있습니다.",
    low: "물가 상승이 예상보다 작습니다. 금리 인하·완화 기대가 커져 국내 성장주·기술주에 우호적일 수 있습니다.",
  },
  KR_BOK: {
    what: "한국은행 기준금리 결정일입니다. 대출 금리·주택 담대·은행 주식에 직접 영향을 줍니다.",
    high: "금리를 올리거나 더 오래 올릴 것이라는 전망입니다. 은행·보험주에는 우호적이고, 고수익·부동산·성장주에는 부담이 될 수 있습니다.",
    low: "금리를 내리거나 더 이상 올리지 않겠다는 전망입니다. 성장주·수출주·기술주에 우호적이며, 은행주에는 단기 압박이 될 수 있습니다.",
    note: "예상보다 ‘높다/낮다’보다, 실제 금리 변경 여부가 중요합니다.",
  },
} as const;

export type MacroGuideCode = keyof typeof macroGuide;

export function getMacroGuide(code: string) {
  return macroGuide[code as MacroGuideCode];
}

export function failedCountLabel(n: number) {
  return `실패 ${n}건`;
}

export function screenFailuresSub(n: number) {
  return ko.screenFailures.sub.replace("{n}", String(n));
}

export function screenFailuresSection(market: "kr" | "us", n: number) {
  const label = market === "kr" ? ko.screenFailures.kr : ko.screenFailures.us;
  return `${label} (${n})`;
}

export function telegramSentSub(n: number) {
  return ko.telegramSent.sub.replace("{n}", String(n));
}

export function telegramSentSection(market: "kr" | "us", n: number) {
  const label = market === "kr" ? ko.telegramSent.kr : ko.telegramSent.us;
  return `${label} (${n})`;
}

export function nextRescanCountdown(time: string) {
  return `다음 재분석 ${time}`;
}
